name: Tests

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Add hosts to /etc/hosts
        run: echo "127.0.0.1 site-1" | sudo tee -a /etc/hosts && echo "127.0.0.1 site-2" | sudo tee -a /etc/hosts

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - run: npm test